# Generated by Django 6.0.2 on 2026-03-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('RENAME', 'Rename'), ('DELETE', 'Delete')], help_text='Type of file operation', max_length=20)),
                ('source', models.CharField(help_text='Storage source (local or s3)', max_length=10)),
                ('file_path', models.CharField(help_text='File path operated on', max_length=500)),
                ('old_path', models.CharField(blank=True, default='', help_text='Original path (for rename operations)', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the operation occurred')),
                ('success', models.BooleanField(default=True, help_text='Whether the operation succeeded')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if operation failed')),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes (if applicable)', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['operation'], name='manager_fil_operati_e39b3c_idx'), models.Index(fields=['source'], name='manager_fil_source_8db766_idx'), models.Index(fields=['timestamp'], name='manager_fil_timesta_50ef0f_idx')],
            },
        ),
    ]
