# Generated by Django 6.0.2 on 2026-03-03 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStorageToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('onedrive', 'Microsoft OneDrive'), ('googledrive', 'Google Drive')], help_text='Cloud storage provider', max_length=20)),
                ('access_token', models.TextField(help_text='OAuth 2.0 access token')),
                ('refresh_token', models.TextField(blank=True, default='', help_text='OAuth 2.0 refresh token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the token was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the token was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='manager_clo_user_id_0737ad_idx')],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
